### ISSUE TITLE
Please add the images file folder as well on the main  branch!!

### ISSUE THREAD

**Issue by atharva100** [Citradev/Eyewear-retail-company-Website#2]
Hey , you haven't added the folder containing all your images to the main code. That's why the images don't show up when i copy all of the code and run it on the live server. 
Please add the images folder once you're free !

**Comment by Citradev** [comment]
Ok I will do it but check my latest repo

**Comment by Citradev** [comment]
Added images

**Comment by atharva100** [comment]
hey citradev please check the updated code and start working on the login page, leave a reply so that i can understand that you've viewed the code

**Comment by atharva100** [comment]
i added all required texts and images

**Comment by atharva100** [comment]
![image](https://user-images.githubusercontent.com/92461125/169535982-a2c3e4c4-9628-4d53-9f25-7fb277891631.png)

**Comment by atharva100** [comment]
lol i had added images 19 days ago, where is the image folder
